services:
  database:
    build:
      context: ./PLOT-DB
    ports:
      - "1433:1433"
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./PLOT-DB
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ready"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  backend:
    build:
      context: ./PLOT-BE
      dockerfile: Dockerfile.dev
    ports:
      - "8085:8085"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./PLOT-BE/Plot:/app
    develop:
      watch:
        - action: sync
          path: ./PLOT-BE/Plot
          target: /app/Plot

  frontend:
    build:
      context: ./PLOT-FE
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./PLOT-FE/Plot:/app
    develop:
      watch:
        - action: sync
          path: ./PLOT-FE/Plot
          target: /app/Plot
