services:
  database:
    build:
      context: ./PLOT-DB
    ports:
      - "1433:1433"
    env_file:
      - .env

  backend:
    build:
      context: ./PLOT-BE
      dockerfile: Dockerfile.dev
    ports:
      - "8085:8085"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./PLOT-BE/Plot:/app
    develop:
      watch:
        - action: sync
          path: ./PLOT-BE/Plot
          target: /app/Plot

  frontend:
    build:
      context: ./PLOT-FE
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./PLOT-FE/Plot:/app
    develop:
      watch:
        - action: sync
          path: ./PLOT-FE/Plot
          target: /app/Plot